In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr[5]

5

In [6]:
arr[6:9]

array([6, 7, 8])

In [8]:
arr[6:9] = 11
print(arr)

[ 0  1  2  3  4  5 11 11 11  9]


In [9]:
# Two-dimensional array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr2d[0][2]

3

In [11]:
arr2d[:,2]

array([3, 6, 9])

In [12]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [15]:
# second row, the first two column
arr2d[1, :2]

array([4, 5])

In [16]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [17]:
#Boolean index
data = np.random.randn(7,4)
print(data)

[[-1.23188306 -1.2718941   1.02852726  0.745051  ]
 [ 0.37263866 -0.93912408  0.19928702 -0.34937023]
 [-0.51770922 -0.62352788  0.03998866 -0.24299688]
 [-0.03612899 -0.54530779 -2.45552261 -0.37794807]
 [ 0.2486856  -1.02083133 -1.12703709  1.6071985 ]
 [-1.04675983  0.18011319 -1.14467109  0.15211803]
 [-1.11114343  0.11069312 -0.41407678 -1.24929224]]


In [18]:
data[data < 0] = 0
print(data)

[[0.         0.         1.02852726 0.745051  ]
 [0.37263866 0.         0.19928702 0.        ]
 [0.         0.         0.03998866 0.        ]
 [0.         0.         0.         0.        ]
 [0.2486856  0.         0.         1.6071985 ]
 [0.         0.18011319 0.         0.15211803]
 [0.         0.11069312 0.         0.        ]]


In [20]:
#Array transpose and axis swap 数组转置和轴对换
arr = np.arange(15).reshape((3,5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [24]:
# Dot product of two arrays.
# Returns the dot product of a and b.
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [25]:
# For multi-dimensional arrays, transpose needs to get a tuple composed of axis numbers to transpose these axes
# 对于多维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置
arr = np.arange(16).reshape(2,2,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [26]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])