In [1]:
import numpy as np

In [3]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [5]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# power calculation equals using function pow() 幂运算
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [11]:
arr2 = np.array([[0,6,3],[11,33,77]])
arr2 > arr

array([[False,  True, False],
       [ True,  True,  True]])