In [10]:
import numpy as np

In [11]:
data = np.random.randn(2,3)
print(data)

[[-0.67745726 -1.28019431  0.04694719]
 [ 0.91148821  0.21441607 -0.62932279]]


In [12]:
data % 10

array([[9.32254274, 8.71980569, 0.04694719],
       [0.91148821, 0.21441607, 9.37067721]])

In [13]:
data + data

array([[-1.35491453, -2.56038862,  0.09389437],
       [ 1.82297643,  0.42883214, -1.25864558]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

change list into array

In [16]:
list1 = [3, 7, 6.5, 2, 10]
arr1 = np.array(list1)
print(arr1)

[ 3.   7.   6.5  2.  10. ]


In [17]:
# Nested data 嵌套数据
list2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(list2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
#dtype of ndarray
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([4.2,5.88,6], dtype=np.int32)
print(arr1)
print(arr2)

[1. 2. 3.]
[4 5 6]


In [24]:
# type INT into type FLOAT
arr = np.array([1,8,9,6,4])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64
